version: "2"

services:

  webserver:
    build: 
      context: ./local-docker-files/webserver
    image: webserver
    # mount point for application in tomcat
    volumes:
      - ./target/Solitare:/usr/local/tomcat/webapps/Solitare
    # open ports for tomcat and remote debugging
    ports:
      - "8080:8080" 
      - "8000:8000"
    links:
      - database:database
    restart: always

  database:
    build:
      context: ./local-docker-files/database
    image: database
    # set default mysql root password, change as needed
    environment:
      MYSQL_ROOT_PASSWORD: password
    # Expose port 3306 to host. Not for the application but
    # handy to inspect the database from the host machine.
    ports:
      - "3306:3306" 
    restart: always
