FROM mysql:5.7

# Default values for passwords and database name. Can be overridden on docker run
# ENV MYSQL_ROOT_PASSWORD=my-secret-pw # Not defaulted for security reasons!
ENV MYSQL_DATABASE=webappdb
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password
